### ISSUE TITLE
prototxt file?

### ISSUE THREAD

**Issue by Liuhua93** [bairdzhang/smallhardface#1]
Nice work and nice code, but I don't find where the prototxt file and solver file?

**Comment by bairdzhang** [comment]
Due to the incorrect .gitignore, the `models` were not uploaded. I've fixed this. Thanks for your remind.
The prototxts are uploaded to `models` (they are not the final version used for training and testing, since `lib/prototxt/manipulate.py` will modify them according to the configurations).
