### ISSUE TITLE
boost/thread.hpp: No such file or directory

### ISSUE THREAD

**Issue by rabysam28** [bairdzhang/smallhardface#11]
I am trying to compile the code and am getting the following error. Would you advice how to resolve it?

src/caffe/internal_thread.cpp:1:28: fatal error: boost/thread.hpp: No such file or directory
compilation terminated.

I am also see the following error about opencv:

Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found

**Comment by bairdzhang** [comment]
Hi, it looks that the compiler cannot find boost headers and opencv. Perhaps you can try to install these dependencies as discussed in [https://caffe.berkeleyvision.org/install_apt.html](https://caffe.berkeleyvision.org/install_apt.html).

**Comment by rabysam28** [comment]
Thanks for the hint. I was able to install caffe, boost and opencv. 
So since my system is cpu, I found this ticket #9 and I am trying to follow your instructions there of how to enable your code to do inference in cpu, however the instructions are not very clear for me, perhaps because I am new to caffe. I was wondering if it is possible you can share your script in which you verified running cpu so that I can use that? I am sure it would be useful for other people as well. Thanks in advance.

**Comment by bairdzhang** [comment]
Very sorry for the delay -- we were having the server relocated and I cannot access my server for the last week. For running on CPU, I've pushed a commit here (https://github.com/bairdzhang/smallhardface/commit/79ac2af3c63443becb345c53f8d9ec75fc5b5949) with the necessary changes. Thanks!
