### ISSUE TITLE
Hard Image

### ISSUE THREAD

**Issue by sunsiyang2015** [bairdzhang/smallhardface#4]
hello, this is an interseting work. 
I want to know where is the source code of finding  hard image ?
Thanks.

**Comment by bairdzhang** [comment]
Hi, it is implemented in https://github.com/bairdzhang/smallhardface/blob/master/lib/layers/multi_layer_anchor_layer.py#L195-L206 and https://github.com/bairdzhang/smallhardface/blob/master/lib/layers/multi_layer_anchor_layer.py#L329-L338 and https://github.com/bairdzhang/smallhardface/blob/master/lib/roi_data_layer/layer.py#L36-L50
