### ISSUE TITLE
About AFW dataset

### ISSUE THREAD

**Issue by kevinisbest** [bairdzhang/smallhardface#7]
Hello, can you provide the AFW dataset and the corresponding annotation? The original [link](https://www.ics.uci.edu/~xzhu/face/) is died. Thanks!

**Comment by bairdzhang** [comment]
Here is the AFW dataset:

https://livejohnshopkins-my.sharepoint.com/:u:/g/personal/zzhang99_jh_edu/EeSCI4tqlAhGkFSzSGex5IEBWmLX4ombENHSrFRymseCiQ?e=pf5Cf1
