### ISSUE TITLE
测试时内存溢出

### ISSUE THREAD

**Issue by shannon233** [bairdzhang/smallhardface#8]
我的机器是GTX1070，显存8G，在数据集测试和demo测试时，scale超过700就报内存溢出，因此在测试widerface数据集时，只能使用[100,300,600]的scale进行测试，请问是我机器显存不够的原因么

**Comment by bairdzhang** [comment]
你好，我测试了下，训练应该需要超过８G，测试的话应该不到６G。根据你的描述，可能是你的caffe编译时没有开cudnn？

**Comment by shannon233** [comment]
确实是这个问题，之前使用apt-get install caffe-cuda安装的caffe，不确定是否使用了cudnn，现在重新编译了caffe，就可以正常测试了，没有scale限制，感谢！！
