### ISSUE TITLE
CPU Only Mode

### ISSUE THREAD

**Issue by ghost** [bairdzhang/smallhardface#9]
Hi, 

I'm trying to use your repo in CPU mode. If I run the demo, I get the error message:
F0423 20:17:33.188555    31 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.

Is there an easy way to enable the CPU only mode other than changing the Makefile? 

Thanks in advance

**Comment by bairdzhang** [comment]
Hi, sorry for the late response. I tried a bit and it is possible to use CPU only to run the demo (but very slow). What I've changed are:
1. In Makefile.config, disable USE_CUDNN & USE_NCCL, set CPU_ONLY and remove CUDA_DIR & CUDA_ARCH.
2. In lib/nms/nms_wrapper.py, remove all gpu_nms part.
3. In lib/setup.py, remove all CUDA part.
4. In the demo function at lib/test.py, remove caffe.set_mode_gpu() and caffe.set_device(cfg.GPU_ID), and add caffe.set_mode_cpu().

This should enable inference on CPU. I am less sure it is possible or feasible to do the training on CPU.
